export const types = Object.freeze({
    LATEST_FILMS_START_FETCHING: 'LATEST_FILMS_START_FETCHING',
    LATEST_FILMS_STOP_FETCHING:  'LATEST_FILMS_STOP_FETCHING',
    LATEST_FILMS_FETCHING_ERROR: 'LATEST_FILMS_STOP_FETCHING',
    LATEST_FILMS_FILLING:        'LATEST_FILMS_FILLING',

});