export const types = Object.freeze({
    TRENDING_FILMS_START_FETCHING: 'TRENDING_FILMS_START_FETCHING',
    TRENDING_FILMS_STOP_FETCHING: 'TRENDING_FILMS_STOP_FETCHING',
    TRENDING_FILMS_FILL_STATE: 'TRENDING_FILMS_FILL_STATE',
    TRENDING_FILMS_SET_FETCHING_ERROR: 'TRENDING_FILMS_SET_FETCHING_ERROR',
    TRENDING_FILMS_FETCH_ASYNC: 'TRENDING_FILMS_FETCH_ASYNC'
});