export const types = Object.freeze({
  // Sync
  START_FETCHING: '[FILM] - START_FETCHING',
  STOP_FETCHING: '[FILM] - STOP_FETCHING',
  SELECTED_FILM_FILL: '[FILM] - SELECTED_FILM_FILL',
  REVIEWS_FILL: '[FILM] - REVIEWS_FILL',
  SIMILAR_FILMS_FILL: '[FILM] - SIMILAR_FILMS_FILL',
  RECOMMENDATION_FILMS_FILL: '[FILM] - RECOMMENDATION_FILMS_FILL',
  MOST_POPULAR_FILM_FILL: '[FILM] - MOST_POPULAR_FILM_FILL',
  SET_FETCHING_ERROR: '[FILM] - SET_FETCHING_ERROR',
  FILM_CLEAN: '[FILM] - FILM_CLEAN',


  //Async
  GET_SELECTED_FILM: '[FILM] - GET_SELECTED_FILM',
  GET_REVIEWS: '[FILM] - GET_REVIEWS',
  GET_SIMILAR_FILMS: '[FILM] - GET_SIMILAR_FILMS',
  GET_RECOMMENDATION_FILMS: '[FILM] - GET_RECOMMENDATION_FILMS',
  GET_MOST_POPULAR_FILM: '[FILM] - GET_MOST_POPULAR_FILM',

})
