export const types = Object.freeze({
  TOP_RATED_START_FETCHING: 'TOP_RATED_START_FETCHING',
  TOP_RATED_STOP_FETCHING: 'TOP_RATED_STOP_FETCHING',
  TOP_RATED_FILL: 'TOP_RATED_FILL',
  TOP_RATED_SET_FETCHING_ERROR: 'TOP_RATED_SET_FETCHING_ERROR'
});
